### ISSUE TITLE
iOS 9 beta isn't fetched

### ISSUE THREAD

**Issue by spitfire** [krypted/precache#1]
iOS 9 beta isn't fetched, even though I didn't supply switch to prevent precache from getting beta updates. As far as I can see the feed url is:
http://mesu.apple.com/assets/seed-R40.Subdivide/com_apple_MobileAsset_SoftwareUpdate/com_apple_MobileAsset_SoftwareUpdate.xml

**Comment by carlashley** [comment]
Hi spitfire,

Beta caching won't be explicitly supported.
